[build]
  publish = "build"
  command = "npm install"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/get"
  to = "/.netlify/functions/get"
  status = 200

[[redirects]]
  from = "/api/post"
  to = "/.netlify/functions/post"
  status = 200

[[redirects]]
  from = "/api/hello"
  to = "/.netlify/functions/hello"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200